/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.EmployeeDirectory;

/**
 *
 * @author jaymithani
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    EmployeeDirectory directory;
    public ViewJPanel(EmployeeDirectory directory) {
        initComponents();
        this.directory = directory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTeam = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtTeam = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtPhoto = new javax.swing.JTextField();

        lblView.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("View Employee Details");
        lblView.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Level", "Team"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        btnView.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnView.setText("View");
        btnView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name");

        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAge.setText("Age");

        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate.setText("Start Date");

        lblTeam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTeam.setText("Team Info");

        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhone.setText("Phone No");

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("ID");

        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender");

        lblLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLevel.setText("Level");

        lblPosition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPosition.setText("Position");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAge)
                                    .addComponent(lblName)
                                    .addComponent(lblDate)
                                    .addComponent(lblTeam)
                                    .addComponent(lblPhone)
                                    .addComponent(lblId)
                                    .addComponent(lblGender)
                                    .addComponent(lblLevel)
                                    .addComponent(lblPosition)
                                    .addComponent(lblEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImage)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtDate, txtEmail, txtGender, txtId, txtLevel, txtName, txtPhone, txtPosition, txtTeam});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmail, lblGender, lblId, lblLevel, lblPhone, lblPosition});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 448, Short.MAX_VALUE)
                        .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImage)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDate)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTeam)
                                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhone)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblId)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLevel)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPosition)
                                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int SelectRowIndex = tblEmp.getSelectedRow();
        
        if(SelectRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete a employee details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblEmp.getModel();
        Employee selectedEmployee =  (Employee) model.getValueAt(SelectRowIndex, 0);
        
        directory.deleteEmployee(selectedEmployee);
        
        JOptionPane.showMessageDialog(this, "Employee details deleted");
        
        populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int SelectRowIndex = tblEmp.getSelectedRow();
        
        if(SelectRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view employee details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblEmp.getModel();
        Employee selectedEmployee =  (Employee) model.getValueAt(SelectRowIndex, 0);
        
        txtAge.setText(String.valueOf(selectedEmployee.getEmpAge()));
        txtName.setText(selectedEmployee.getEmpName());
        txtId.setText(selectedEmployee.getEmpId());
        txtGender.setText(selectedEmployee.getEmpGender());
        txtDate.setText(selectedEmployee.getEmpStartDate());
        txtLevel.setText(selectedEmployee.getEmpLevel());
        txtTeam.setText(selectedEmployee.getEmpTeamInfo());
        txtPosition.setText(selectedEmployee.getEmpPosition());
        txtPhone.setText(selectedEmployee.getEmpCellPhoneNumber());
        txtEmail.setText(selectedEmployee.getEmpEmailAddress());
        //txtImage.setText(selectedEmployee.getEmpPhoto());
        lblPhoto.setIcon(resize_image(selectedEmployee.getEmpPhoto()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        int selectedRowIndex = tblEmp.getSelectedRow();
        
        if(selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select row to update employee details");
            return;
        }
                
        DefaultTableModel model= (DefaultTableModel) tblEmp.getModel();
        Employee selectedEmployee = (Employee) model.getValueAt(tblEmp.getSelectedRow(),0);
        
        /*if(tblEmployee.getSelectedRowCount() < 0)
        {
            JOptionPane.showMessageDialog(this,"Please select Employee Data to Update.");
            return;
        }*/        
        if(tblEmp.getSelectedRowCount()==1)
        {
            if (validateFields()){
                String Name= txtName.getText();
                String Employeeid = txtId.getText();
                int Age = Integer.parseInt(txtAge.getText());
                String Gender = txtGender.getText();
                String StartDate = txtDate.getText();
                String Level = txtLevel.getText();
                String TeamInfo = txtTeam.getText();
                String PositionTitle = txtPosition.getText();
                String CellPhone = txtPhone.getText();
                String Email = txtEmail.getText();
                //String Photo = txtPhoto.getText();

                selectedEmployee.setEmpName(Name);
                selectedEmployee.setEmpId(Employeeid);
                selectedEmployee.setEmpAge(Age);
                selectedEmployee.setEmpGender(Gender);
                selectedEmployee.setEmpStartDate(StartDate);
                selectedEmployee.setEmpLevel(Level);
                selectedEmployee.setEmpTeamInfo(TeamInfo);
                selectedEmployee.setEmpPosition(PositionTitle);
                selectedEmployee.setEmpCellPhoneNumber(CellPhone);
                selectedEmployee.setEmpEmailAddress(Email);
                //selectedEmployee.setEmpPhoto(Photo);

                model.setValueAt(Name,tblEmp.getSelectedRow(), 0);
                model.setValueAt(Employeeid,tblEmp.getSelectedRow(), 1);
                //model.setValueAt(Age,tblEmp.getSelectedRow(), 2);
                //model.setValueAt(Gender,tblEmp.getSelectedRow(), 3);
                //model.setValueAt(StartDate,tblEmp.getSelectedRow(), 4);
                model.setValueAt(Level,tblEmp.getSelectedRow(), 2);
                model.setValueAt(TeamInfo,tblEmp.getSelectedRow(), 3);
                //model.setValueAt(PositionTitle,tblEmp.getSelectedRow(), 7);
                //model.setValueAt(CellPhone,tblEmp.getSelectedRow(), 8);
                //model.setValueAt(Email,tblEmp.getSelectedRow(), 9);
                //model.setValueAt(Photo,tblEmp.getSelectedRow(), 10);

                System.out.println(" Breakpoint");

                JOptionPane.showMessageDialog(this,"Employee Details upadted successfully");

                populateTable();

                txtName.setText("");
                txtId.setText("");
                txtAge.setText("");
                txtGender.setText("");
                txtDate.setText("");
                txtLevel.setText("");
                txtTeam.setText("");
                txtPosition.setText("");
                txtPhone.setText("");
                txtEmail.setText("");
            }
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private boolean validateFields(){
        if(!(Pattern.matches("(?i)(^[a-z][a-z]*[a-z]$)|(?i)(^[a-z][a-z]*\\s[a-z][a-z]*\\s[a-z]*[a-z]$)|(?i)(^[a-z][a-z]*\\s[a-z]*[a-z]$)|(?i)(^[a-z][a-z]*\\s[a-z][a-z]*\\s[a-z][a-z]*\\s[a-z]*[a-z]$)", txtName.getText()))){
            JOptionPane.showMessageDialog(null, "Name : Incorrect characters used", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(!(Pattern.matches("^[0-9]+$", txtId.getText()))){
            JOptionPane.showMessageDialog(null, "EmpId : ID should be in numbers", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if (!(Pattern.matches("^[0-9]+$", txtAge.getText()))) 
         {
             JOptionPane.showMessageDialog(null, "Age should be in integers", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
        else if (Integer.parseInt(txtAge.getText())<0) 
         {
             JOptionPane.showMessageDialog(null, "Age cannot be less than 0", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
        else if (Integer.parseInt(txtAge.getText())<18 || Integer.parseInt(txtAge.getText())>99) 
         {
             JOptionPane.showMessageDialog(null, "Enter age between 18 to 99", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
        else if(!(Pattern.matches("^(?i)^[a-z]+$", txtGender.getText()))){
            JOptionPane.showMessageDialog(null, "Gender : Incorrect characters used", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(!(Pattern.matches("^([0][1-9]|[1][0-2])[\\/]([0][1-9]|[1][0-9]|[2][0-9]|[3][0-1])[\\/]([0-9]{4})$", txtDate.getText()))){
            JOptionPane.showMessageDialog(null, "Date should be in dd/mm/yyyy format", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(!(Pattern.matches("^(?i)[a-z0-9]+$", txtLevel.getText()))){
            JOptionPane.showMessageDialog(null, "Level should be in alphanumeric", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if (!(Pattern.matches("^(?i)([a-z][a-z]*[0-9]*@\\w+[.][a-z]+)$", txtEmail.getText()))) {
            JOptionPane.showMessageDialog(null, "Incorrect Email format", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if (!Pattern.matches("^(\\+1)?[0-9]{10}$", txtPhone.getText())) 
        {
            JOptionPane.showMessageDialog(null, "Phone number should be 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{
            return true;
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lblView;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtTeam;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmp.getModel();
        model.setRowCount(0);
        
        for (Employee e : directory.getDirectory()){
            Object[] row= new Object[4];
            row[0] = e;
            row[1] = e.getEmpId();
            row[2] = e.getEmpLevel();
            row[3] = e.getEmpTeamInfo();
            model.addRow(row);
        }
        
    }

    private Icon resize_image(String empPhoto) {
        ImageIcon image_icon = new ImageIcon(empPhoto);
        Image img = image_icon.getImage();
        Image new_image = img.getScaledInstance(300,144,Image.SCALE_SMOOTH);
        ImageIcon new_image_icon = new ImageIcon(new_image);
        return new_image_icon;    
    }
}
